food/urls.py
from . import views
from .views import IndexClassView
from django.urls import path

app_name = 'food'

urlpatterns = [
    path('', IndexClassView.as_view(), name = 'index'),
    path('item/', views.item, name = 'item'),
    path('info/', views.info, name = "info"),
    path('<int:item_id>/', views.detail, name = "detail" ),
    #add form
    path('add', views.CreateItem.as_view(), name = "create"),
    #edit item
    path('update/<int:id>/', views.update_item, name = 'update_item'),
    #delete item
    path(r'^delete/<int:id>/', views.delete_item, name = 'delete_item')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name = "register"),
    path('login/', authentication_views.LoginView.as_view(template_name = 'users/login.html'), name = 'login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name = 'users/logout.html'), name = 'logout'),
    path('profile/', user_views.profilepage, name = "profile"),
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models

class Item(models.Model):
    
    def __str__(self):
        return self.item_name
    
    item_name = models.CharField(max_length = 200)
    item_desc = models.CharField(max_length= 200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default ="https://i.jamesvillas.co.uk/images/jvh/holiday-destinations/resort/food-placeholder.jpg" )

    

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default = 'profilepic.jpg', upload_to= 'profile_pictures')
    location = models.CharField(max_length=100) 

    def __str__(self):
        return self.user.username

food/forms.py
from django.forms import ModelForm
from .models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'

class FoodDetailView(DetailView):
    model = Item
    template_name = 'food/detail.html'


def item(request):
    return HttpResponse("This  is an item view.")

def info(request):
    return HttpResponse("I am loving this song called: Ngwa!")

def detail(request, item_id):
    item = Item.objects.get(pk = item_id)
    context = {
        'item' : item,
    }
    return render(request, 'food/detail.html', context)

#this is a class based view for create_item
class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image' ]#We only specify those fields which we want to be present in our form
    template_name = 'food/item-form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return redirect('')

def update_item(request, id):
    item = Item.objects.get(id = id)
    form = ItemForm(request.POST or None, instance = item)
    if (form.is_valid()):
        form.save()
        return redirect('food:index')

    return render(request, 'food/item-form.html', {'form': form, 'item': item} )

def delete_item(request, id):
    item = Item.objects.get(id = id)

    if (request.method == 'POST'):
        item.delete()
        return redirect('food:index')
    return render(request, 'food/item-delete.html', {'item': item})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm
# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}, your account is now created.')
            return redirect('food:index')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request, 'users/profile.html')

food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel = "stylesheet" href =" {% static 'food/style.css' %} ">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
        <nav class = "navbar navbark-dark bg-dark">
                <a href ="#" class="navbar-brand">AppConfig!</a>
        
                <div class="navbar">
                    <a class="nav-item nav-link" href = "add">New item</a>
                    <a class="nav-item nav-link" href = "#">Delete</a>
                    <a class="nav-item nav-link" href = "#">Replace</a>
                    {% if user.is_authenticated %}
                        <a href = "{% url 'logout' %}" >Logout</a>
                        <a href = "{% url 'profile' %}">Profile</a>
                    {% else %}
                        <a href = "{% url 'login' %}">Login</a>
                    {% endif %}
                </div>
            </nav>
            {% if messages %}
                {% for message in messages %}
                <div class = "alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
                    
                {% endfor %}
            {% endif %}
    {% block body %}
    {% endblock %}
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    
</head>
<body>
    {% block body %}
    <div class="container">
        <div class = "row">
            <div class = "col-md-6">
                <img height = "300px" src = "{{ item.item_image }}" class = "card" />

            </div>
            <div class = "col-md-6">
                    <h1>{{ item.item_name }}</h1>
                    <h2> {{ item.item_desc }}</h2>
                    <h3> ${{ item.item_price }}</h3>
                    <a href = "{% url 'food:delete_item' item.id %}" >Delete</a>
            </div>
        </div>
    </div>
    {% endblock %}
</body>
</html>

food/templates/food/index.html
{% extends 'food/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel = "stylesheet" href = {% static 'food/style.css' %} > 
</head>
<body>
    <nav class = "navbar navbar-dark bg-dark">
        <a href = '#' class "navbar-brand">App Configuration</a>

        <div class = "navbar">
            <a class="nav-item nav-link" href ='#' >Menu</a>
            <a class="nav-item nav-link" href ='#' >New Request</a>
            <a class="nav-item nav-link" href ='#' >Go!</a>

        </div>
    </nav>

    {% block body %}
    {% for item in item_list %}
    <div class = "row">
        <div class = "col-md-3 offset-md-2">
            <img class = "card" height = "150px" width="200px" src = "{{ item.item_image }}" />
            
        </div>

        <div class ='col-md-4'>
            <h3>{{item.item_name}}</h3>
            <h5> {{ item.item_desc }}</h5>
            <h6> {{ item.item_price }}</h6>
        </div>
        <div class = "col-md-2">
             <a href ="{{ item.id }}" class="btn btn-success">Details</a>
        </div>
    </div>





    {% endfor %}   
    {% endblock %}

</body>
</html>

food/templates/food/item-delete.html
<form method = "POST">
    {% csrf_token %}
    <h2>Are you like damn sure that you want to delete {{ item.item_name }}!?</h2>
    <button>Confirm</button>
</form>

food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<div class = "container">
    <div class = "row">
        <div class = "col-md-4 offset-md-4">
        <div class = "card">
            <div class="card-header text-white bg-info">
                <div class="card-title">
                    Add food items
                </div>
            </div>
            <div class="card-body">
                <form method = "POST">
                    <form method = "POST">
                        {% csrf_token %}
                    {% for field in form %}
                        <div class = "form-group">
                            {{ field.name }}
                            {{ field }}
                        </div>
                    {% endfor %}
                        <button type= "Submit" >Save</button>
                    </form>
                </form>
            </div>
        </div>
    </div>
    </div>
</div>

{% endblock %}

users/templates/users/login.html
{% extends 'food/base.html' %}
{% load static %}
{% block body %}
<div class = "container">
    <div class = "row">
        <div class = "col-md-4 offset-md-4">
        <div class = "card">
            <div class="card-header text-white bg-info">
                <div class="card-title">
                    Login
                </div>
            </div>
            <div class="card-body">
                <form method = "POST">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class = "form-group">
                            {{ field.name }}
                            {{ field }}
                        </div>
                    {% endfor %}
                    <button class="btn-info" type = "submit">Login</button>
                </form>
            </div>
        </div>
    </div>
    </div>
</div>

{% endblock %}

users/templates/users/logout.html
<h1> You have been logged out </h1>

users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img width = '600px' height = '600px' src = "{{ user.profile.image.url }}">

users/templates/users/register.html
{% extends 'food/base.html' %}
{% load static %}
{% block body %}

<div class = "container">
    <div class = "row">
        <div class = "col-md-4 offset-md-4">
        <div class = "card">
            <div class="card-header text-white bg-info">
            </div>
            <div class="card-body">
                    <form method = "POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                <br>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button class="btn-info" type = "submit">Signup</button>
                    </form>
                </form>
            </div>
        </div>
    </div>
    </div>
</div>

{% endblock %}









{ endblock }